apiVersion: v1
kind: Pod
metadata:
  name: srvrep1
spec:
  containers:
    - name: task-pv-container
      image: docker.io/library/server:pfe
      #command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
      ports:
        - containerPort: 80
          name: "http-server"
      resources:
        requests:
          memory: "64Mi"
          cpu: "1000m"
        limits:
          memory: "128Mi"
          cpu: "1000m"

