apiVersion: apps/v1
kind: Deployment
metadata:
  name: pas-deployment
  labels:
    app: pas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pas
  template:
    metadata:
      labels:
        app: pas
    spec:
      containers:
      - name: pas
        image: docker.io/library/server:pfe
        ports:
        - containerPort: 80
          name: "http-server"
        resources:
          requests:
            memory: "64Mi"
            cpu: "1000m"
          limits:
            memory: "128Mi"
            cpu: "1000m"          
